apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetspa-depl
spec:
  selector:
    matchLabels:
      app: kwetterspa
  template:
    metadata:
      labels:
        app: kwetterspa
    spec:
      containers:
        - name: kwetterspa
          image: siem228/kwetterspa
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: kwetterspa-srv
spec:
  selector:
    app: kwetterspa
  ports:
    - name: kwetterspa
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kwetterspadb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kwetterspadb
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 400Mi