apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetterspa-depl
spec:
  selector:
    matchLabels:
      app: kwetterspa
  template:
    metadata:
      labels:
        app: kwetterspa
    spec:
      containers:
        - name: kwetterspa
          image: siem228/kwetterspa
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: kwetterspa-srv
spec:
  type: LoadBalancer
  selector:
    app: kwetterspa
  ports:
    - name: kwetterspa
      protocol: TCP
      port: 3000
      targetPort: 3000
